FROM {{ namespace }}/{{ image_prefix }}prometheus-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block pushgateway_header %}{% endblock %}

{% block pushgateway_repository_version %}
ARG pushgateway_version=1.11.1
{% if debian_arch == 'arm64' %}
ARG pushgateway_sha256sum=b6dc1c1c46d1137e5eda253f6291247e39330d3065a839857b947e59b4f3e64b
{% else %}
ARG pushgateway_sha256sum=6ce6ffab84d0d71195036326640295c02165462abd12b8092b0fa93188f5ee37
{% endif %}
ARG pushgateway_url=https://github.com/prometheus/pushgateway/releases/download/v{$pushgateway_version}/pushgateway-${pushgateway_version}.linux-{{debian_arch}}.tar.gz
{% endblock %}

{% block pushgateway_install %}
RUN curl -o /tmp/pushgateway.tar.gz ${pushgateway_url} \
    && echo "${pushgateway_sha256sum} /tmp/pushgateway.tar.gz" | sha256sum -c \
    && tar xvf /tmp/pushgateway.tar.gz -C /opt/ \
    && rm -f /tmp/pushgateway.tar.gz \
    && ln -s /opt/pushgateway* /opt/pushgateway
{% endblock %}

{% block pushgateway_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER prometheus