FROM {{ namespace }}/{{ image_prefix }}manila-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block manila_share_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.enable_extra_repos(['ceph', 'epel']) }}

{% if base_package_type == 'rpm' %}
    {% set manila_share_packages = [
        'ceph-common',
        'glusterfs-fuse',
        'sqlite',
        'nfs-ganesha',
        'nfs-ganesha-ceph',
        'nfs-ganesha-utils',
        'nfs-ganesha-rados-urls',
        'nfs-ganesha-rados-grace',
        'dbus-x11'
    ] %}
{% elif base_package_type == 'deb' %}
    {% set manila_share_packages = [
        'ceph-common',
        'glusterfs-client',
        'python3-cephfs',
        'python3-rados',
        'python3-rbd',
        'sqlite3',
        'nfs-ganesha',
        'nfs-ganesha-utils',
    ] %}

{% endif %}

{{ macros.install_packages(manila_share_packages | customizable("packages")) }}

COPY extend_start.sh /usr/local/bin/kolla_manila_extend_start

RUN chmod 644 /usr/local/bin/kolla_manila_extend_start && mkdir -p /var/run/ganesha && chmod 755 /usr/bin/ganesha.nfsd &&  echo "manila ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

{% block manila_share_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER manila
