[DEFAULT]
install_type = source

[ovsdpdk-plugin-ovs]
type = local
location = package/ovs.tar.gz

[ovsdpdk-plugin-dpdk]
type = local
location = package/dpdk.tar.gz

[ovsdpdk-plugin-mlx]
type = local
location = package/mlx-ofe-so.tar.gz

[ovsdpdk-plugin-mlxib]
type = local
location = package/infiniband.tar.gz
