[neutron-base]
type = git
location = https://github.com/dingodb/neutron.git
reference = base2025.1-bmgw

[openstack-base]
type = local
location = package/requirements-stable-2025.1.tar.gz

[neutron-base-plugin-networking-baremetal]
type = local
location = package/networking-baremetal-stable-2025.1.tar.gz

[neutron-base-plugin-networking-generic-switch]
type = local
location = package/networking-generic-switch-stable-2025.1.tar.gz

[neutron-base-plugin-networking-sfc]
type = local
location = package/networking-sfc-stable-2025.1.tar.gz

[neutron-base-plugin-vpnaas-agent]
type = local
location = package/neutron-vpnaas-stable-2025.1.tar.gz

[neutron-bgp-dragent]
type = local
location = package/neutron-dynamic-routing-stable-2025.1.tar.gz

[neutron-server-plugin-neutron-dynamic-routing]
type = local
location = package/neutron-dynamic-routing-stable-2025.1.tar.gz

[neutron-vpnaas-agent]
type = local
location = package/neutron-vpnaas-stable-2025.1.tar.gz
